import asyncio
import os
import sys
import random
from datetime import datetime, timedelta

# Add app to path
sys.path.append(os.path.join(os.path.dirname(__file__), ".."))

from app.core.db import engine
from sqlmodel import select
from sqlmodel.ext.asyncio.session import AsyncSession
from app.models.wishlist import Wishlist, WishlistItem
from app.models.product import Product

async def seed_wishlist():
    print("Starting wishlist seeding...")
    
    async with AsyncSession(engine) as session:
        # Get all products
        products_res = await session.exec(select(Product))
        products = products_res.all()
        if not products:
            print("No products found to wish for.")
            return

        product_ids = [p.id for p in products]
        
        # We need users. We will simulate user_ids from 1 to 200
        # If user does not exist in users table, it might be fine for Wishlist logic 
        # since product-fastapi doesn't enforce user_id foreign key constraint directly 
        # (user_id is just an integer managed by api-gateway/auth).
        
        user_ids = list(range(1, 201))
        
        # Clear existing wishlist data generated by seed if any?
        # Better just clear all for simplicity or add to them.
        # Requirements: "Generate 200 users and 500+ items using seed_wishlist.py"
        
        total_items_added = 0
        
        for user_id in user_ids:
            # Check if user already has a wishlist
            wishlist_res = await session.exec(select(Wishlist).where(Wishlist.user_id == user_id))
            wishlist = wishlist_res.first()
            if not wishlist:
                wishlist = Wishlist(user_id=user_id)
                session.add(wishlist)
                await session.commit()
                await session.refresh(wishlist)
                
            # Randomly select 2 to 6 products for this user
            num_products = random.randint(2, 6)
            wished_products = random.sample(product_ids, num_products)
            
            for pid in wished_products:
                # check if already wished
                existing_res = await session.exec(
                    select(WishlistItem)
                    .where(WishlistItem.wishlist_id == wishlist.id)
                    .where(WishlistItem.product_id == pid)
                )
                existing = existing_res.first()
                
                if not existing:
                    # Random date within last 60 days
                    days_ago = random.randint(0, 60)
                    created_at = datetime.utcnow() - timedelta(days=days_ago)
                    
                    item = WishlistItem(
                        wishlist_id=wishlist.id,
                        product_id=pid,
                        created_at=created_at
                    )
                    session.add(item)
                    total_items_added += 1
                    
            if user_id % 50 == 0:
                print(f"Processed {user_id} users...")
                await session.commit()
                
        await session.commit()
        
    print(f"✅ Seeding completed! Added {total_items_added} wishlist items for {len(user_ids)} users.")

if __name__ == "__main__":
    asyncio.run(seed_wishlist())
