spring.application.name=shop
spring.datasource.url=jdbc:postgresql://localhost:5432/shop_db
spring.datasource.username=shop_user
spring.datasource.password=shop_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update


spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.app.jwtExpirationMs=100000000
spring.app.jwtSecret=tranphuclong123287138asdalsjdklajs80912839081290381290381jkasjekljaslkdjkalsjdlas01823
spring.app.jwtCookieName=jwtCookie


image.base.url=http://localhost:8080/images
image.upload.dir=uploads/images

# File upload limits
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB

# SePay Configurations
sepay.merchant.bank=MB
sepay.merchant.account=0987654321
sepay.webhook.apikey=SEPAY_SECURE_TOKEN_12345