spring.application.name=shop
spring.datasource.url=jdbc:postgresql://localhost:5432/shop_db
spring.datasource.username=shop_user
spring.datasource.password=shop_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update


spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect