spring.application.name=shop
spring.datasource.url=jdbc:postgresql://localhost:5432/shop_db
spring.datasource.username=shop_user
spring.datasource.password=shop_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update


spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.app.jwtExpirationMs=100000000
spring.app.jwtSecret=tranphuclong123287138asdalsjdklajs80912839081290381290381jkasjekljaslkdjkalsjdlas01823
spring.app.jwtCookieName=jwtCookie


image.base.url=http://localhost:8080/images