FROM golang:1.25.5-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o api-gateway main.go

FROM alpine:latest

WORKDIR /app
COPY --from=builder /app/api-gateway .

EXPOSE 8080
CMD ["./api-gateway"]
