"""Add realistic ecommerce metadata fields

Revision ID: 638893d9609d
Revises: 18dccc749b29
Create Date: 2026-05-27 04:43:12.102757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '638893d9609d'
down_revision: Union[str, Sequence[str], None] = '18dccc749b29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('brand', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.add_column('products', sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True))
    op.add_column('products', sa.Column('rating', sa.Float(), nullable=False))
    op.add_column('products', sa.Column('reviews_count', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('discount_percent', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('is_featured', sa.Boolean(), nullable=False))
    op.add_column('products', sa.Column('is_bestseller', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'is_bestseller')
    op.drop_column('products', 'is_featured')
    op.drop_column('products', 'discount_percent')
    op.drop_column('products', 'reviews_count')
    op.drop_column('products', 'rating')
    op.drop_column('products', 'image_url')
    op.drop_column('products', 'brand')
    # ### end Alembic commands ###
