"""Add total_sold column

Revision ID: d890945df21c
Revises: 9757dabdb945
Create Date: 2026-05-27 04:58:07.038568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd890945df21c'
down_revision: Union[str, Sequence[str], None] = '9757dabdb945'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('total_sold', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'total_sold')
    # ### end Alembic commands ###
